### ISSUE TITLE
Logging overhaul

### ISSUE THREAD

**Issue by sampsyo** [sampsyo/beets#1044]
It's time for a significant change in how logging works in beets. Namely:

* [x] Using `str.format()`-style templating for logging currently requires eager calls (i.e., we have to format strings that will never be displayed). This is (a) inefficient, (b) error-prone, causing potential crashes even when the log message will just be thrown away anyway in non-verbose mode, and (c) inconvenient to type. Instead, we should provide a logging configuration that does this by default. (See #916.)
* [x] Plugins should be able to easily prefix their messages with the plugin name. Currently, we have to type `log.info('replaygain: hello')`; the plugin API should provide a child logger that does this automatically with `self.log.info('hello')`. Bonus points if we automatically adjust the log level for the plugin according to whether it's running as an import hook or as a special command. (See #431.)
* [x] A good fraction of bugs filed with beets are Unicode errors due to formatting bytes in a logging string (i.e., missing `displayable_path` calls). We should provide loggers that can transparently decode bytes to Unicode.
* [ ] More granular logging levels (#430, #327) would also be nice.

**Comment by brunal** [comment]
I started looking into the subject. I noted the following problems:
- usages of `log.error("Problem occured: {}", exc)` instead of `log.exception("Problem occured")`
- usages of `log.info("{0} {1}", foo.bar, foo.baz)` instead of `log.info("{0.bar} {0.baz}", foo)`

**Comment by brunal** [comment]
I think that we now have a strong base on which advancing on granular log levels should be easy (related to issues #327, #430, #431 → not knowing where to discuss it, I picked here).

##### Current status
Right now there are 2 ways to control logging:
- `-v` that logs at debug-level
- `log` config option (and `-l` option) that pick a log file

##### Desired behaviour
- pick all logging levels (warning/info/logging) for all loggers: base and plugins
- pick a logging level for each plugin, as well as a logging target (dedicated file for a given plugin)
- if a plugin has its own logging conf (level, file), should its logs be present in the base log as well?
- what am I forgetting?

**Comment by sampsyo** [comment]
Thank *you* for the tremendous amount of reorganization it took to make that work! You deserve some kind of award. :sparkles:

I'm not totally clear what the most useful next step would be. In particular, I'm not actually certain that we need to expose universal, per-plugin configurability (level and target). Do you have any use cases in mind where this would be useful?

It seems like the requests, e.g. in #327, center around providing at least one more global level of verbosity. For example, `-v` could provide a bit more detail while `-vv` would provide an overwhelming amount of detail useful only for debugging.

Finally, #431 touches on a feature that would be useful in general: logging all the verbose messages to a file while printing only relevant messages to a console. This wouldn't need to be per-plugin configurable; it would just be nice to have a place to look for details when something goes wrong without leaving `-v` on all the time. We could even ask people to upload this file with their bug reports if it's enabled by default!

One exception is the "import log" feature, which is currently a completely separate piece of logic used only for writing down import decisions. Maybe this should be rolled into the general logging framework.

**Comment by brunal** [comment]
That's my pleasure :-)

The biggest use case I have in mind for a wholly configuration logging is debugging for plugin developers, though `self._log.setLevel(logging.DEBUG)` does the job just fine.

IMHO the import log should be managed by a standard logger.

**Comment by sampsyo** [comment]
All the pieces are now in place, so I'm closing this discussion issue. More granular configuration can live on in #430 and #327.
